// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_ABOUT  1001
#define IDR_MNU_MAIN  2001
#define IDM_ABOUT  6001
#define IDM_OPEN  6002
#define IDR_ICO_MAIN  8001

#include "irrp.h"
